import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Prompt Hive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[#F5EBEB]">
        <main>{children}</main>

        <Toaster />
      </body>
    </html>
  );
}
