import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/homePage/navbar/Navbar";
import Footer from "@/components/homePage/footer/Footer";

export const metadata = {
  title: "Prompt Hive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
